### ISSUE TITLE
-- More -- prompt handling

### ISSUE THREAD

**Issue by kz282** [ssinyagin/gerty#5]
There are some device types, where the -- More -- prompt can't be disabled. I have created a small patch that presses a space in case the more prompt is matched. The remains of the more prompt are cleaned from the command output content.

My solution is a bit rough as the more prompt attribute must be defined.

```
diff -u GenericAction.pm.orig GenericAction.pm
--- GenericAction.pm.orig       2012-08-10 13:42:10.000000000 +0200
+++ GenericAction.pm    2012-08-10 20:29:16.000000000 +0200
@@ -49,7 +49,7 @@
     foreach my $attr
         ( 'admin-mode', 'cli.timeout', 'cli.user-prompt', 'cli.admin-prompt',
           'cli.comment-string', '+cli.command-actions', 'cli.error-regexp',
-          '+cli.handler-mixins')
+          '+cli.handler-mixins','more-prompt','more-prompt-clean')
     {
         $self->{$attr} = $self->device_attr($attr);
     }
@@ -162,6 +162,7 @@
     $exp->send($cmd . "\r");
     my $result = $exp->expect
         ( $self->{'cli.timeout'},
+          ['-re', $self->{'more-prompt'},sub {$exp->send(" ");$exp->set_accum($exp->before());exp_continue;}],
           ['-re', $self->{'prompt'}],
           ['timeout', sub {$failure = 'Connection timeout'}],
           ['eof', sub {$failure = 'Connection closed'}]);
@@ -187,6 +188,8 @@
     my $content = $exp->before();
     $content =~ s/\r\n/\n/ogm;

+    $content =~ s/$self->{'more-prompt-clean'}//gm;
+
     # outcomment the command from the top if it was echoed
     if( index($content, $cmd) == 0 and defined($self->{'cli.comment-string'}) )
     {
```

**Comment by hudecof** [comment]
Are there any news ?
I have the same issue with FortiOS ;(

**Comment by ssinyagin** [comment]
@hudecof not really. I can make an expensive offer to fix this, or you find someone to fix it :)

**Comment by hudecof** [comment]
@ssinyagin I already did and testing it on FortiOS. Seems to be working, alt least on my 2 devices.

**Comment by hudecof** [comment]
I got small problem to with `SPACE` as value in the INI file.
If I try `'  '` or `" "` it does not work. 
I'm testing on 3com 4500g, wgere any other key on the `MORE` prompt stops the paging ;(

tried to  check also `Config::Any` docs, but without success. I do not want to set this key hardcoded.

**Comment by ssinyagin** [comment]
we can just define a new parameter, like `cli.more-prompt-continue-space = 1`
Can I have a look at your changes in the code? I see you forked the gerty repo, but didn't commit anything. Also as I proposed, it makes sense to create a new package for specific vendors.

**Comment by hudecof** [comment]
I will add the code in CiscoLike.pm class.
For the 3com 4500G I have new class with redefined all variables.

The code is not finished `->` no commit ;)
I will add `cli.more-prompt-continue-space = 1`, seems to be better solution as my current.

**Comment by hudecof** [comment]
I created branch i my repo for this
`https://github.com/hudecof/gerty/commits/add-paging-support`.

I need to test default values for cisco and add documentation.

**Comment by hudecof** [comment]
see https://github.com/ssinyagin/gerty/pull/16
